name: flutter_lyawei
description: Flutter学习demos

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fluttertoast: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
  - family: 自定义字体
    fonts:
    - asset: assets/fonts/LillyBelle.ttf
  - family: 安娜一号中文
    fonts:
    - asset: assets/fonts/安娜一号中文.ttf

